### ISSUE TITLE
Extend functions.yml format

### ISSUE THREAD

**Issue by burner1024** [sfall-team/sfall#453]
I have a suggestion to further detalize function data by splitting `detail` into separate fields.
That would allow to provide signature help:

![Peek 2023-01-24 12-18](https://user-images.githubusercontent.com/1279852/214217468-02267a13-341e-46fe-b618-3983856e15d7.gif)

The format would change like this:

old
```yaml
- name: disable_aimed_shots
  detail: void disable_aimed_shots(int pid)
  opcode: 0x823f
  doc: Allows overriding the normal rules regarding which weapons are allowed to make aimed attacks. (e.g. weapons that cause explosive damage normally cannot normally make aimed shots.) stops a weapon from making aimed shots even if it normally coulld. Affects player and NPCs alike. The list of edited weapons is not saved over game loads, so you need to call the function once at each reload. Use a pid of 0 to represent unarmed.
```
new
```yaml
- name: disable_aimed_shots
  type: void
  opcode: 0x823f
  args:
    - type: int
      name: pid
      doc: Weapon PID. 0 means unharmed.
#      default: 123 # this arg has no default, omitted.
  doc: Allows overriding the normal rules regarding which weapons are allowed to make aimed attacks. (e.g. weapons that cause explosive damage normally cannot normally make aimed shots.) stops a weapon from making aimed shots even if it normally coulld. Affects player and NPCs alike. The list of edited weapons is not saved over game loads, so you need to call the function once at each reload.
```

The proposal is only to allow this format, not to convert everything at once, hopefully that can happen naturally over time.

Another thing I'd like to suggest is to allow an optional `deprecated` string field, which could be used to do, well, deprecations.
![Captura desde 2023-01-24 12-24-29](https://user-images.githubusercontent.com/1279852/214218220-ff3b660e-0b57-4b39-b18f-1a60292b27ff.png)
